# Generated by Django 5.0.4 on 2024-05-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("cash_collector", "0001_initial"),
	]

	operations = [
		migrations.AlterField(
			model_name="customer",
			name="address",
			field=models.TextField(blank=True),
		),
		migrations.AlterField(
			model_name="customer",
			name="email",
			field=models.EmailField(blank=True, max_length=254),
		),
		migrations.AlterField(
			model_name="customer",
			name="phone",
			field=models.CharField(blank=True, max_length=15),
		),
	]
