# Generated by Django 5.0.4 on 2024-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("cash_collector", "0003_transaction_created_at_transaction_deleted_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="user",
			name="auth_token",
			field=models.CharField(blank=True, max_length=100, null=True),
		),
	]
