# Generated by Django 5.0.4 on 2024-05-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("auth", "0012_alter_user_first_name_max_length"),
		("cash_collector", "0004_user_auth_token"),
	]

	operations = [
		migrations.AlterField(
			model_name="task",
			name="amount_due",
			field=models.DecimalField(decimal_places=2, max_digits=10),
		),
		migrations.AlterField(
			model_name="task",
			name="amount_due_at",
			field=models.DateTimeField(),
		),
		migrations.AlterField(
			model_name="task",
			name="is_collected",
			field=models.BooleanField(default=False),
		),
		migrations.AlterField(
			model_name="transaction",
			name="amount",
			field=models.DecimalField(decimal_places=2, max_digits=10),
		),
		migrations.AlterField(
			model_name="user",
			name="groups",
			field=models.ManyToManyField(
				blank=True,
				related_name="cash_collector_user_set",
				related_query_name="user",
				to="auth.group",
				verbose_name="groups",
			),
		),
		migrations.AlterField(
			model_name="user",
			name="is_frozen",
			field=models.BooleanField(default=False),
		),
		migrations.AlterField(
			model_name="user",
			name="user_permissions",
			field=models.ManyToManyField(
				blank=True,
				related_name="cash_collector_user_set",
				related_query_name="user",
				to="auth.permission",
				verbose_name="user permissions",
			),
		),
	]
