# Generated by Django 5.0.4 on 2024-05-04 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("cash_collector", "0005_alter_task_amount_due_alter_task_amount_due_at_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="task",
			name="manager",
			field=models.ForeignKey(
				default=None,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="tasks_created",
				to="cash_collector.user",
			),
			preserve_default=False,
		),
	]
