# Generated by Django 5.0.4 on 2024-05-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("cash_collector", "0006_task_manager"),
	]

	operations = [
		migrations.AddField(
			model_name="user",
			name="manager",
			field=models.ForeignKey(
				blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cash_collector.user"
			),
		),
		migrations.AlterField(
			model_name="transaction",
			name="task",
			field=models.ForeignKey(
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				related_name="transactions",
				to="cash_collector.task",
			),
		),
	]
